version: '3.8'

services:
  # Base de données MySQL
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: healthcare_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql   # sauvegarde les données
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  # Ton application Spring Boot
  app:
    build: ./medical-system
    ports:
      - "8080:8080"
    environment:
      # "mysql" = le nom du service Docker ci-dessus
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/healthcare_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy   # attend que MySQL soit prêt

volumes:
   mysql_data: